###net_radio inputs###
radio_station:
  name: 'Select Radio Station'
  options:
    - BBC Radio 1
    - BBC Radio 4
    - BBC 6 Music

speakers:
  name: 'Select Speakers'
  options:
    - Living Room
    - Bedroom
    - Garden
#    - Ceiling Speakers
  icon: mdi:speaker-wireless

###light_setup###
lights:
  name: 'Select Light'
  options:
    - Amy Bedside
    - Bill Bedside
    - Porch Light
  icon: mdi:lightbulb-on

light_sets:
  name: 'Pre-set Options'
  options:
    - daytime
    - evening
    - bedtime
